{"uuid": "d065b0df-a825-47e1-bd54-f562b1b5dc04", "children": ["ca88a95e-6696-4807-89fd-f6d9f42b28a3"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "TypeError: RemoteConnection.__init__() got an unexpected keyword argument 'resolve_ip'\n", "trace": "  File \"C:\\Users\\V\\PycharmProjects\\SimbirSoft\\.venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"C:\\Users\\V\\PycharmProjects\\SimbirSoft\\.venv\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"C:\\Users\\V\\PycharmProjects\\SimbirSoft\\.venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\V\\PycharmProjects\\SimbirSoft\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1122, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\V\\PycharmProjects\\SimbirSoft\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 877, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"C:\\Users\\V\\PycharmProjects\\SimbirSoft\\tests\\conftest.py\", line 14, in driver\n    command_executor = RemoteConnection(grid_url, resolve_ip=False, keep_alive=True)\n                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n"}, "start": 1715185473070, "stop": 1715185473070}], "start": 1715185473070, "stop": 1715185473167}